### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by dharp** [szaghi/VTKFortran#21]
When I try to compile the code, I get:

make: **\* No rule to make target 'penf.F90', needed by 'static/obj/penf.o'.  Stop.

It looks like the PENF source files are missing. Am I doing something wrong?

Thanks,
Dylan

**Comment by szaghi** [comment]
Dear @dharp 

Thank you for pointing it out. Make is not the main building system, I often forget to update it when the project is modified. Let me few hours and I'll fix it (probably I moved third party dependencies like PENF without updating the makefile, FoBiS does not need such maintenance :smile: )

See you very soon.

**Comment by dharp** [comment]
Thanks Stefano!

--
Dylan R. Harp
Computational Earth Science Group
Earth and Environmental Sciences Division
Los Alamos National Laboratory

(505) 667-5532
Mail Stop T003
Los Alamos National Laboratory
--

**Comment by szaghi** [comment]
@dharp 

I have just upload a patch to the master branch. There are some modifications with respect the older version:

+ into the `src/lib/` directory the sym link to third-party sources have been removed;
+ FoBiS and GNU Make should now work equally;
+ CMake could be broken (@victorsndvg can you check this?)

In the next release I will *sanitize* the tree and add an *automatic* install script.

### Bullet-proof debug mode not working

For testing the new makefile I checked the *paranoiac* bullet-proof compilation against the current tests-suite

> in bullet-proof debug-mode the tests-suite **FAILS**

Probably there are bug into FoXy, I have to investigate, but currently I have not free slot for it, sorry.

@dharp Can you check if the new makefile work for you?

**Comment by dharp** [comment]
Hi Stefano,

I’m now getting:

make: *** No rule to make target `src/third_party/BeFoR64/src/lib/befor64.F90', needed by `static/obj/befor64.o'.  Stop.

--
Dylan R. Harp
Computational Earth Science Group
Earth and Environmental Sciences Division
Los Alamos National Laboratory

(505) 667-5532
Mail Stop T003
Los Alamos National Laboratory
--

**Comment by szaghi** [comment]
I have to update the doc damn me! The submodules must be update after the
repo is cloned. Try this

git clone --recursive http...
cd VTKFortran
git submodule update --init --recursive

Il 11/ott/2016 23:58, "Dylan Robert Harp" <notifications@github.com> ha
scritto:

**Comment by dharp** [comment]
Ok, makes it a lot farther now with gcc 5.4.0:

susfto-eddy:VTKFortran$ make

 Compiler used  gnu => /usr/bin/gfortran
 Source dir     src/
  Lib dir        ./static/
  Libray         ./static/libvtkfortran.a
  Shared lib     no
  Debug          no
  F-standard     no
  Optimize       no
  OpenMP         no
  MPI            no
  R16P           (Known R16P switch) Used R16P=no

 Compile options
 [-cpp -c -J./static/mod/ ]

 Link options
 [ ]

 Compile penf_global_parameters_variables.F90
 Compile penf_b_size.F90
 Compile penf_stringify.F90
 Compile penf.F90
 Compile befor64_pack_data_m.F90
 Compile befor64.F90
 Compile stringifor_string_t.F90
f951: internal compiler error: Segmentation fault
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
makefile:383: recipe for target 'static/obj/stringifor_string_t.o' failed
make: *** [static/obj/stringifor_string_t.o] Error 1





--
Dylan R. Harp
Computational Earth Science Group
Earth and Environmental Sciences Division
Los Alamos National Laboratory

(505) 667-5532
Mail Stop T003
Los Alamos National Laboratory
--

**Comment by szaghi** [comment]
arghhh... I am not sure, but it is possiboe that [StringiFor](https://github.com/szaghi/StringiFor) now requires GNU gfortran 6.x+ (the doc says 5.3 but my doc is often not in sync with my fingers...). I am currently using 6.1.1 and 7.0.0 testing. Your ICE sounds like some F2008 features not supported by GNU 5.3. As a matter of fact it works with 6.x trunk see [travis log](https://travis-ci.org/szaghi/VTKFortran#L681). I'll check tomorror, now I am going to :sleeping_bed: 

See you tomorrow, good night.

**Comment by victorsndvg** [comment]
Hi @szaghi ,

I will need some time to change the CMake compilation system. I think that the right way to implement it is using the `externalproject` feature of CMake. To use this feature I need to create a CMake compilation system for all third party projects (**BeFoR64, FoXy, PENF, StringiFor**).

If it's ok for you, I will try to implement it as soon as possible. But currently I'm very very bussy ...

**Comment by szaghi** [comment]
@victorsndvg Absolutely no rush, take all time you want. Mine was just a remainder for you because I do not use CMake, but with the new modifications I think I have broken your CMake setup. For CMake you are my boss, on the contrary I have to thank you for adding a feature that many people like. 

Cheers.

**Comment by victorsndvg** [comment]
Yes, you are right, CMake build system of VTKFortran is currently broken. I will fix it as soon as possible.

Thanks to you for your great libs, I'm using them in almost all my projects :grimacing:

**Comment by szaghi** [comment]
> Thanks to you for your great libs, I'm using them in almost all my projects ￼

I am really sorry for you :smile:
