### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by jnmchck** [szaghi/VTKFortran#23]
Dear szaghi,

i am very interested in your fortran library for writing vtk-files.

Unfortunately i get the following error when trying to compile the source code:

```
src/lib/vtk_fortran_parameters.f90:7:4:

 use penf
    1
Fatal Error: Can't open module file ‘penf.mod’ for reading at (1): Datei oder Verzeichnis nicht gefunden
compilation terminated.

src/lib/vtk_fortran_parameters.f90:7:4:

 use penf
    1
Fatal Error: Can't open module file ‘penf.mod’ for reading at (1)
```

I installed FoBiS and tried to build like this: `FoBiS.py build -mode static-gnu-debug`
(`FoBiS.py build -mode static-gnu` didn't work neither)

Thank you in advance,
Regards
Jan

**Comment by szaghi** [comment]
Hi Jan, 

I am out of office until September, thus I cannot help you efficiently with my smartphone, please be patient.

Anyhow, at a first glance it seems that you do not have all the third party dependencies like PENF. Try to update the submodule like:

> git submodules update --init

( I am not sure about the syntax, but it should be something about the above)

See you soon and thanks for the patience.

**Comment by jnmchck** [comment]
Hi Stefano,
(Sorry for mistaking your name at the first time)

now everything works fine. Thank you.

**Comment by szaghi** [comment]
Hi Jan,

do not worry for the name :-)

I am happy that all work well now.

See you soon.

**Comment by szaghi** [comment]
Thank you @ekeyser
