### ISSUE TITLE
xml_writer%write_geo does not write the points section if nc>np

### ISSUE THREAD

**Issue by AliE89** [szaghi/VTKFortran#30]
Ciao Stefano,

Hope you are doing well. I am facing a wired issue using your library. 

I am using your library  (it is very cool!) and up to now I have not faced any issue. Today, I had one which I suspect to be a bug.

I am trying to write a unstructured mesh of 14 points, 24 cells, cell type is  tetrahedron (cell_type=10). I am able to get a geometry unitl np > nc, but suddendly, if nc>np, write_geo does not write the points section in the xml file.  

To be clear, if I build  the mesh until the cell n° 14,  I can see the points section, while if I use 15 cells, It disappears... This is true for every format (ascii, binary or raw). 

Any idea about this Stefano?   

Thank you for your help! :)

**Comment by AliE89** [comment]
Stefano, I can confirm that the problem is when nc>np. Have you got some sort of check that prevents the code to write the points down? I just added a couple of dommy points in order to have np>nc and it worked.

**Comment by szaghi** [comment]
Hi @AliE89 

> Stefano, I can confirm that the problem is when nc>np. Have you got some sort of check that prevents the code to write the points down? I just added a couple of dommy points in order to have np>nc and it worked.

You are right, there is a silly check, I do not know why I had introduced it, I am going to fix this bug, I hope to finish it today.

Thank you very much for pointing it out.

Cheers

**Comment by AliE89** [comment]
Thanks Stefano, 

I have found out where you check for the number of cells in in 4 procedure in vtk_fortran_vtk_file_xml_writer_abstract. Removing that looks like make the thing working. I will re-pull the lib with you official fix in any case!

**Comment by szaghi** [comment]
@AliE89 

I have already removed the check. Let me few hours, I am merging other branches and pulling a new release today

**Comment by AliE89** [comment]
This sounds like a plan! Fortran people have to offer you a beer ;)

**Comment by szaghi** [comment]
@AliE89 @smelch000 @rnelias @victorsndvg 

I have just uploaded a new release: there is the bug fix for this issue and the new *volatile* file method for enabling the library to be used into a parallel scenario where only one (master) process has access to the filesystem. It should be fully backward compatible. I have made minor code lint and I have updated the makefile.

I hope to update soon the documentation for the 2.x branch.

Let me know if you find any issues.

Cheers

**Comment by AliE89** [comment]
Cool, many thanks Stefano!

**Comment by smelch000** [comment]
Thank you Stefano, very appreciated !

**Comment by victorsndvg** [comment]
Great job @szaghi ! Thanks!

**Comment by AliE89** [comment]
Ciao Stefano,

I am personally getting an error while compiling under gfortran: 

" src/lib/vtk_fortran_vtk_file_xml_writer_abstract.f90:658:42:

       xml_volatile = self%xml_volatile%raw
                                          1
Error: Component ‘raw’ at (1) is a PRIVATE component of ‘string’
make: *** [makefile:424: static/obj/vtk_fortran_vtk_file_xml_writer_abstract.o] Error 1 "

I think this is related to the volatile changes you mentioned. 

Sorry, I keep messing you up :)

**Comment by szaghi** [comment]
> Ciao Stefano,
> 
> I am personally getting an error while compiling under gfortran:
> 
> " src/lib/vtk_fortran_vtk_file_xml_writer_abstract.f90:658:42:
> 
> ```
>    xml_volatile = self%xml_volatile%raw
>                                       1
> ```
> 
> Error: Component ‘raw’ at (1) is a PRIVATE component of ‘string’
> make: *** [makefile:424: static/obj/vtk_fortran_vtk_file_xml_writer_abstract.o] Error 1 "
> 
> I think this is related to the volatile changeCiao Stefano,

I am personally getting an error while compiling under gfortran:

" src/lib/vtk_fortran_vtk_file_xml_writer_abstract.f90:658:42:

```
   xml_volatile = self%xml_volatile%raw
                                      1
```

Error: Component ‘raw’ at (1) is a PRIVATE component of ‘string’
make: *** [makefile:424: static/obj/vtk_fortran_vtk_file_xml_writer_abstract.o] Error 1 "

I think this is related to the volatile changes you mentioned.

Sorry, I keep messing you up :)s you mentioned.
> 
> Sorry, I keep messing you up :)

Hi @AliE89 

you have probably an older version (commit) of StringiFor, another of my libraries used by VTKFortran. As you can see here

https://github.com/szaghi/StringiFor/blob/master/src/lib/stringifor_string_t.F90#L25

`raw` member of string class is now public (in old versions it was private). I guess that your third-party libraries of VTKFortran is not all up-to-date.

I suggest to go into each third-party libraries and check that they are aligned with the latest master branch, e.g. for StringiFor library:

```bash
cd src/third_party/
cd StringiFor/
git checkout master
git pull
```

I have adopted a simple choice: all my libraries work together by means of all the latest master branch (this help me a lot, I am being alone).

Let me know if this fix your problem.

Cheers

**Comment by AliE89** [comment]
Sure, It was that :) all good then! Let you known if working with the library I find something else to fix! Thanks!

**Comment by szaghi** [comment]
> Sure, It was that :) all good then! Let you known if working with the library I find something else to fix! Thanks!

thank you very much!

See you soon

**Comment by szaghi** [comment]
I closed this issue, it seems ok now.

Feel free to reopen it or a new one for any problems.

Cheers
